### ISSUE TITLE
Default settings for HDR

### ISSUE THREAD

**Issue by Boulder08** [4re/resamplehq#1]
Would it be possible to have the option to tell the resizer that the source (and destination) contains HDR material and have the matrices adjusted accordingly? It could also be useful to define SD and HD the same way, SD being anything with width 720 pixels or less and HD 1920 pixels or less.

**Comment by 4re** [comment]
Looking into it. Would this values be correct?
```python
    if hdr is True:
        if matrix is None:
            matrix = '2020ncl'
        if transfer is None:
            transfer = 'st2084'
    else:
        if height <= 576:
            if matrix is None:
                matrix = '470bg'
            if transfer is None:
                transfer = '601'
        else:
            if matrix is None:
                matrix = '709'
            if transfer is None:
                transfer = '709'
```

**Comment by Boulder08** [comment]
Better use width <= 720 and width <=1920 I think (at least height < 720 is not correct, it's <= 576 for SD PAL).

HDR probably also needs a separate parameter to use HD values even if the resolution is over FullHD. There's some material which is released as 4K but SDR (for example Stranger Things first season).

**Comment by 4re** [comment]
That should be OK (I updated first comment).

**Comment by Boulder08** [comment]
Yes, that looks good to me too.

**Comment by 4re** [comment]
Done.
