### ISSUE TITLE
typo in code?

### ISSUE THREAD

**Issue by andrewbedia** [4re/resamplehq#2]
When calling the function as follows in a .vpy, it complains about RGBS not defined on line 134

```
from vapoursynth import core
import resamplehq as rshq
video = rshq.resample_hq(clip=video,height=960,width=720)
```

The fix seems to be changing line 1 in resamplehq.py to be 
`from vapoursynth import core, RGB, RGBH, RGBS`

instead of
`from vapoursynth import core, RGB, RGBH, RGBH`

**Comment by 4re** [comment]
Oops... indeed. Should be fixed now.
