### ISSUE TITLE
Python exception '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by AIisCool** [4re/resamplehq#3]
Hi, I'm trying to use this script but having this error:

```
C:\Users\User\AppData\Roaming\Python\Python39\site-packages\resamplehq.py", line 124, in resamplehq
if height <= 576:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

Thanks.

**Comment by 4re** [comment]
Are you properly feeding a video to it? It looks like it finds it has no height attribute. Full script?

**Comment by 4re** [comment]
Sorry brain fart. This is a resizer, the problem is you are not giving it a height parameter for the destination resolution.
